---
title: "clustering.Rmd"
author: "Zack Poorman"
date: "11/13/2020"
output: html_document
---

```{r}
library(tidyverse)
db <- readxl::read_xlsx("DB Schema UPDATED.xlsx")
```

```{r}
#Function that normalizes numerical data for clustering
minMax <- function(v){return((v-min(v))/(max(v)-min(v)))}

frontlinePriceConvert_Existing_Data <- function(data){
  formatted <- db%>%
    select(NonNational)%>%
    mutate(MMNonNational = minMax(NonNational))
  return(formatted)
}

dba <- frontlinePriceConvert_Existing_Data(db)
  
#Manually update BevType to 0-1 with associated columns
test <- db%>%
  mutate(BevType2 = BevType)%>%
  pivot_wider(names_from = "BevType2", values_from="BevType2", names_repair="unique")%>%
  mutate(
    "NEW AGE BEVERAGE" = ifelse(`NEW AGE BEVERAGE` %in% "NEW AGE BEVERAGE",1,0),
    "CRAFT BEER" = ifelse(`CRAFT BEER` %in% "CRAFT BEER",1,0),
    "IMPORT BEER" = ifelse(`IMPORT BEER` %in% "IMPORT BEER",1,0),
    "PREMIUM BEER" = ifelse(`PREMIUM BEER` %in% "PREMIUM BEER",1,0)
  )

#Function that takes in a dataset (from the file that gets uploaded)
#and converts the BevTypes to 0-1 in their respective columns 
bevTypeConvert_Existing_Data <- function(data){
  formatted <- data%>%
  mutate(BevType2 = BevType)%>%
  pivot_wider(names_from = "BevType2", values_from="BevType2", names_repair="unique")%>%
  mutate(
    "NEW AGE BEVERAGE" = ifelse(`NEW AGE BEVERAGE` %in% "NEW AGE BEVERAGE",1,0),
    "CRAFT BEER" = ifelse(`CRAFT BEER` %in% "CRAFT BEER",1,0),
    "IMPORT BEER" = ifelse(`IMPORT BEER` %in% "IMPORT BEER",1,0),
    "PREMIUM BEER" = ifelse(`PREMIUM BEER` %in% "PREMIUM BEER",1,0)
  )
  return(formatted)
}

#Checking the function and it works
dba <- bevTypeConvert_Existing_Data(db)

#Manually updates Package to 0-1 with associated columns
db%>%
  mutate(Package2 = Package)%>%
  pivot_wider(names_from = "Package2", values_from="Package2", names_repair="unique")%>%
  mutate(
    "23.5OZ (24)" = ifelse(`23.5OZ (24)` %in% "23.5OZ (24)",1,0),
    "20OZ (24)" = ifelse(`20OZ (24)` %in% "20OZ (24)",1,0),
    "1/6BBL KEG" = ifelse(`1/6BBL KEG` %in% "1/6BBL KEG",1,0),
    "12OZ BTL 4/6PK" = ifelse(`12OZ BTL 4/6PK` %in% "12OZ BTL 4/6PK",1,0),
    "12OZ BTL 2/12PK" = ifelse(`12OZ BTL 2/12PK` %in% "12OZ BTL 2/12PK",1,0),
    "12OZ CAN 4/6PK" = ifelse(`12OZ CAN 4/6PK` %in% "12OZ CAN 4/6PK",1,0),
    "18.6OZ (12)" = ifelse(`18.6OZ (12)` %in% "18.6OZ (12)",1,0),
    "1/2BBL KEG" = ifelse(`1/2BBL KEG` %in% "1/2BBL KEG",1,0),
    "13.2GL KEG" = ifelse(`13.2GL KEG` %in% "13.2GL KEG",1,0),
    "16.9OZ (20)" = ifelse(`16.9OZ (20)` %in% "16.9OZ (20)",1,0)
  )

#Function that takes in a dataset (from the file that gets uploaded)
#and converts the Package to 0-1 in their respective columns
packageConvert_Existing_Data <- function(data){
  formatted <- data%>%
  mutate(Package2 = Package)%>%
  pivot_wider(names_from = "Package2", values_from="Package2", names_repair="unique")%>%
  mutate(
    "23.5OZ (24)" = ifelse(`23.5OZ (24)` %in% "23.5OZ (24)",1,0),
    "20OZ (24)" = ifelse(`20OZ (24)` %in% "20OZ (24)",1,0),
    "1/6BBL KEG" = ifelse(`1/6BBL KEG` %in% "1/6BBL KEG",1,0),
    "12OZ BTL 4/6PK" = ifelse(`12OZ BTL 4/6PK` %in% "12OZ BTL 4/6PK",1,0),
    "12OZ BTL 2/12PK" = ifelse(`12OZ BTL 2/12PK` %in% "12OZ BTL 2/12PK",1,0),
    "12OZ CAN 4/6PK" = ifelse(`12OZ CAN 4/6PK` %in% "12OZ CAN 4/6PK",1,0),
    "18.6OZ (12)" = ifelse(`18.6OZ (12)` %in% "18.6OZ (12)",1,0),
    "1/2BBL KEG" = ifelse(`1/2BBL KEG` %in% "1/2BBL KEG",1,0),
    "13.2GL KEG" = ifelse(`13.2GL KEG` %in% "13.2GL KEG",1,0),
    "16.9OZ (20)" = ifelse(`16.9OZ (20)` %in% "16.9OZ (20)",1,0)
  )
  return(formatted)
}

#Testing the function and it works
dba <- packageConvert_Existing_Data(dba)

#Manually updates Frequency Label to 0-1 with associated columns
db%>%
  mutate(FreqLbl2 = FreqLbl)%>%
  pivot_wider(names_from = "FreqLbl2", values_from="FreqLbl2", names_repair="unique")%>%
  mutate(
    "MEDIUM" = ifelse(`MEDIUM` %in% "MEDIUM",1,0),
    "HIGH" = ifelse(`HIGH` %in% "HIGH",1,0),
    "LOW" = ifelse(`LOW` %in% "LOW",1,0)
  )

#Function that takes in a dataset (from the file that gets uploaded)
#and converts the Frequency Label to 0-1 in their respective columns
frequencyConvert_Existing_Data <- function(data){
  formatted <- data%>%
  mutate(FreqLbl2 = FreqLbl)%>%
  pivot_wider(names_from = "FreqLbl2", values_from="FreqLbl2", names_repair="unique")%>%
  mutate(
    "MEDIUM" = ifelse(`MEDIUM` %in% "MEDIUM",1,0),
    "HIGH" = ifelse(`HIGH` %in% "HIGH",1,0),
    "LOW" = ifelse(`LOW` %in% "LOW",1,0)
  )
  return(formatted)
}

#Testing the function and it works
dba <- frequencyConvert_Existing_Data(db)

kmeans(dba[,27:43], centers = 2)
```